[package]
name = "bedroom-dimmer"
version = "0.1.0"
authors = ["Tim van Dalen <Tim@timvdalen.nl>"]
edition = "2018"
default-run = "dimmer"

[dependencies]
dotenv = "0.15.0"
tiny_http = "0.7.0"

[dependencies.philipshue]
version = "0.3.2"
default-features = false
